

debug-plugin-messages: true

debug-storage: false

debug-copyable: false

debug-menu: false

debug-db: false

backup-minutes: 10 

save-worlds: true

save-players: false

no-join-message: true
custom-join-message: false
on-join-message: '&6O jogador &e$player &6entrou no server'

no-quit-message: true
custom-quit-message: false
on-quit-message: '&6O jogador &e$player &6saiu do server'

no-death-message: true
custom-death-message: false
on-death-player-message: '&6O jogador &e$killer matou o jogador $player'


custom-motd: false

custom-motd-amount: -1
motd:
- seja bem vindo
- Ao meu servidor!

auto-respawn: false
auto-rejoin: false

commands-blocked:
- /comandobloqueado

tab-commands-blocked: 
- /tabbloqueado


